Version: 1
# top level packages
Packages:
  - pillar
  - R6


# any repositories, order matters
Repos:
  - CRAN: "https://cran.microsoft.com/snapshot/2019-11-01"
  - CRAN2: "https://cran.microsoft.com/snapshot/2020-05-01"

Library: "test-library"

Customizations:
  Packages:
    - pillar:
        Type: source
        Suggests: false
        Repo: CRAN2
    - R6:
        Type: binary
        Suggests: true
        Repo: CRAN
  Repos:
    - CRAN:
        Type: source
